import type { FormEvent } from 'react';
import { api, humanBytes, message } from './api.js';
import { Modal, Icon, Alert, Skeleton, Field } from './components.js';
import type { Candidate, Runtime, Doctor, ResourcePreview, Metrics, Stack, Observed, LogLine, Operation, Group } from './types.js';
const { useState, useEffect, useRef } = React;
export function DiscoverDialog({ roots, stacks, onClose, onSelect, onRoots }: {roots: string[]; stacks: Stack[]; onClose: () => void; onSelect: (candidates: Candidate[]) => void; onRoots: () => void}) {
  const [root,setRoot] = useState(roots[0] || ''), [depth,setDepth] = useState('8');
  const [candidates,setCandidates] = useState<Candidate[]>([]), [selected,setSelected] = useState<string[]>([]), [error,setError] = useState(''), [busy,setBusy] = useState(false), [result,setResult] = useState('');
  const controller = useRef<AbortController | null>(null); useEffect(() => () => controller.current?.abort(), []);
  async function scan(e: FormEvent) {
    e.preventDefault(); controller.current?.abort(); controller.current = new AbortController(); const signal = controller.current.signal;
    setBusy(true);setError('');setResult('');setCandidates([]);setSelected([]);
    try {
      const added = await api<{root: string}>('/roots',{root},signal);setRoot(added.root);onRoots();
      const response = await api<{candidates: Candidate[]; entries: number; truncated: boolean; warnings: string[]}>('/discover',{root:added.root,depth:Number(depth)},signal);
      setCandidates(response.candidates);setResult(`${response.candidates.length} aplicaciones posibles · ${response.entries} entradas revisadas${response.truncated ? ' · Límite alcanzado: usa una raíz más concreta.' : ''}${response.warnings.length ? ' · ' + response.warnings.join(' · ') : ''}`);
    } catch(e) {if (!signal.aborted) setError(message(e));} finally {if (controller.current?.signal === signal) setBusy(false);}
  }
  const selectable = candidates.filter(c => !stacks.some(s => s.path === c.path));
  return <Modal title="Descubrir aplicaciones" subtitle="1. Busca en tu carpeta. 2. Selecciona las aplicaciones. 3. Revisa su configuración y añádelas a un grupo." onClose={onClose} wide>
    <form onSubmit={e => void scan(e)}><Field label="Carpeta raíz" help="Carpeta que contiene tus proyectos, por ejemplo ~/Projects. Se revisan subcarpetas; no se ejecuta ni se modifica ningún repositorio."><input required autoFocus value={root} onChange={e => setRoot(e.target.value)} list="roots" placeholder="~/Projects"/></Field><datalist id="roots">{roots.map(r => <option key={r} value={r}/>)}</datalist>
      <details className="advanced compact-details"><summary>Opciones de búsqueda</summary><Field label="Profundidad de búsqueda" help="Cuántos niveles de subcarpetas recorrer. 8 suele ser suficiente; 0 revisa solo la carpeta elegida. Se omiten dependencias, cachés y enlaces a directorios."><input type="number" min="0" max="20" value={depth} onChange={e => setDepth(e.target.value)}/></Field></details>
      <div className="inline-actions"><button className="primary" disabled={busy}><Icon name="search"/>{busy ? 'Buscando…' : 'Buscar aplicaciones'}</button>{busy && <button type="button" onClick={() => {controller.current?.abort();setBusy(false);}}>Cancelar búsqueda</button>}</div>
    </form>
    {error && <Alert error>{error}</Alert>}{busy && <Skeleton label="Buscando aplicaciones en tus carpetas" rows={5}/>}
    {result && <><div className="scan-result" role="status">{result}</div>{selectable.length > 0 && <label className="check-label"><input type="checkbox" checked={selected.length === selectable.length && selectable.length > 0} onChange={e => setSelected(e.target.checked ? selectable.map(c => c.path).slice(0,32) : [])}/>Seleccionar aplicaciones disponibles (máximo 32)</label>}</>}
    <div className="candidate-list">{candidates.map(c => {const known = stacks.find(s => s.path === c.path); return <label className={`candidate selectable ${selected.includes(c.path) ? 'selected' : ''}`} key={c.path}>
      <input aria-label={`Seleccionar ${c.relative}`} type="checkbox" disabled={Boolean(known) || selected.length >= 32 && !selected.includes(c.path)} checked={selected.includes(c.path)} onChange={e => setSelected(e.target.checked ? [...selected,c.path] : selected.filter(v => v !== c.path))}/><Icon name="folder" size={22}/><span className="candidate-description"><strong>{c.relative}</strong><code>{c.files.join(' · ')}</code><small>{known ? `Ya registrada como ${known.id}. Configúrala desde Aplicaciones.` : c.ambiguous ? 'Hay varias bases o variantes: elige la combinación en el siguiente paso.' : 'Se propone el archivo base; puedes añadir variantes al revisar.'}</small></span>
    </label>;})}</div>
    {result && !candidates.length && <Alert>No se encontraron archivos Compose. Comprueba la raíz o aumenta la profundidad. Un Dockerfile sin Compose no define por sí solo cómo levantar la aplicación.</Alert>}
    {!result && !busy && <div className="empty small"><Icon name="search" size={30}/><p>Selecciona, por ejemplo, el frontend y el backend de Máximo Puntaje para registrarlos juntos. Cada aplicación conserva su propio Compose.</p></div>}
    <div className="modal-actions"><span className="selection-count">{selected.length} seleccionadas</span><button onClick={onClose}>Cerrar</button><button className="primary" disabled={!selected.length || busy} onClick={() => onSelect(candidates.filter(c => selected.includes(c.path)))}>Configurar selección <Icon name="chevron" size={14}/></button></div>
  </Modal>;
}
export function GroupDialog({ group, onClose, onSaved }: {group?: Group; onClose: () => void; onSaved: () => void}) {
  const [name,setName] = useState(group?.name || ''), [busy,setBusy] = useState(false), [error,setError] = useState('');
  return <Modal title={group ? 'Renombrar grupo' : 'Crear grupo'} subtitle="Un grupo organiza aplicaciones; no crea contenedores, redes ni dominios." onClose={onClose}><form onSubmit={e => {e.preventDefault();setBusy(true);setError('');void api(group ? '/groups/rename' : '/groups',{id:group?.id,name}).then(onSaved).catch(e => setError(message(e))).finally(() => setBusy(false));}}>
    <Field label="Nombre del grupo" help={group ? `Su identificador CLI (${group.id}) y las identidades Docker no cambian.` : 'Por ejemplo, Máximo Puntaje. Después puedes añadir aplicaciones desde Descubrir o mover las existentes desde Configurar.'}><input required maxLength={120} autoFocus value={name} onChange={e => setName(e.target.value)} placeholder="Máximo Puntaje"/></Field>
    {error && <Alert error>{error}</Alert>}<div className="modal-actions"><button type="button" onClick={onClose}>Cancelar</button><button className="primary" disabled={busy}>{busy ? 'Guardando…' : 'Guardar grupo'}</button></div>
  </form></Modal>;
}
export function RuntimeView({ runtime, connected, operations, onSaved, notify }: {runtime: Runtime; connected: boolean; operations: Operation[]; onSaved: () => void; notify: (value: string, error?: boolean) => void}) {
  const [doctor,setDoctor] = useState<Doctor | null>(null), [metrics,setMetrics] = useState<Metrics | null>(null);
  const [loadingDoctor,setLoadingDoctor] = useState(true), [loadingMetrics,setLoadingMetrics] = useState(true), [busy,setBusy] = useState(false), [error,setError] = useState('');
  const [settings,setSettings] = useState(runtime), [memory,setMemory] = useState('2'), [cpus,setCpus] = useState('2');
  const [preview,setPreview] = useState<ResourcePreview | null>(null), [updates,setUpdates] = useState<{status:string;message:string;items:{name:string;installed:string[];latestKnown:string;command:string}[]} | null>(null);
  const requests = useRef<AbortController | null>(null);
  const operationKey = operations.filter(o => o.action.startsWith('runtime-')).slice(0,3).map(o => `${o.id}:${o.state}`).join('|');
  const runtimeBusy = operations.some(o => o.state === 'running' && o.action.startsWith('runtime-'));
  const dirtySettings = JSON.stringify(settings) !== JSON.stringify(runtime);
  async function load() {
    requests.current?.abort(); const ctrl = new AbortController(); requests.current = ctrl; setLoadingDoctor(true);setLoadingMetrics(true);setError('');
    await Promise.allSettled([
      api<Doctor>('/doctor',undefined,ctrl.signal).then(d => {if (!ctrl.signal.aborted) {setDoctor(d);if(d.allocation){setMemory(String(d.allocation.memoryGiB));setCpus(String(d.allocation.cpus));}}}).catch(e => {if (!ctrl.signal.aborted) setError(message(e));}).finally(() => {if (!ctrl.signal.aborted) setLoadingDoctor(false);}),
      api<Metrics>('/metrics',undefined,ctrl.signal).then(m => {if (!ctrl.signal.aborted) setMetrics(m);}).catch(e => {if (!ctrl.signal.aborted) setError(message(e));}).finally(() => {if (!ctrl.signal.aborted) setLoadingMetrics(false);}),
    ]);
  }
  useEffect(() => {setSettings(runtime);void load(); return () => requests.current?.abort();}, [runtime.kind,runtime.context,runtime.profile,connected,operationKey]);
  async function task(work: () => Promise<void>) {setBusy(true);setError('');try {await work();} catch(e) {setError(message(e));} finally {setBusy(false);}}
  const cannotChange = busy || runtimeBusy || loadingDoctor || dirtySettings;
  const colimaState = doctor?.colima?.state;
  const colimaRunning = colimaState === 'running';
  return <div className="runtime-view"><div className="section-heading"><div><h1>Runtime y recursos</h1><p>Colima mantiene una VM compartida. NearProd permanece fuera de ella.</p></div><button onClick={() => void load()} disabled={busy || loadingDoctor || loadingMetrics}><Icon name="refresh"/>{loadingDoctor || loadingMetrics ? 'Actualizando…' : 'Actualizar diagnóstico'}</button></div>
    {error && <Alert error>{error}</Alert>}{dirtySettings && <Alert>Hay cambios de contexto sin guardar. Guárdalos o descártalos antes de administrar Colima; los datos mostrados siguen correspondiendo al contexto guardado.</Alert>}
    {runtimeBusy && <Alert>Hay una operación global de Colima en curso. Los controles quedan bloqueados hasta que termine; consulta Actividad.</Alert>}
    <div className="runtime-grid"><section className="panel"><div className="panel-heading"><Icon name="settings"/><h2>Dónde se ejecutan tus contenedores</h2></div>
      <form onSubmit={e => {e.preventDefault();void task(async () => {await api('/runtime/settings',settings);onSaved();notify('Contexto guardado. No se cambió el contexto global de Docker.');});}}>
        <Field label="Tipo de runtime" help="En Mac, Colima ejecuta Docker en Linux. Docker local corresponde a Linux/WSL2; no elimina la necesidad de VM en macOS."><select disabled={runtimeBusy} value={settings.kind} onChange={e => setSettings({...settings,kind:e.target.value as Runtime['kind']})}><option value="colima">Colima (macOS)</option><option value="native">Docker local (Linux / WSL2, experimental)</option></select></Field>
        <Field label="Contexto Docker" help="Nombre de la conexión que utilizará NearProd. Puedes verlo con docker context ls; no cambies este valor para crear una VM nueva."><input required disabled={runtimeBusy} value={settings.context} onChange={e => setSettings({...settings,context:e.target.value})}/></Field>
        {settings.kind === 'colima' && <Field label="Perfil Colima" help="Identifica la VM existente; normalmente default. No es un perfil de servicios Compose."><input required disabled={runtimeBusy} value={settings.profile} onChange={e => setSettings({...settings,profile:e.target.value})}/></Field>}
        <div className="inline-actions"><button disabled={busy || runtimeBusy || !dirtySettings}>Guardar contexto</button>{dirtySettings && <button type="button" onClick={() => setSettings(runtime)}>Descartar cambios</button>}</div><p className="hint">Solo conexiones locales por socket Unix. Un catálogo vinculado no se cambia a otro Engine silenciosamente.</p>
      </form>
    </section><section className="panel"><div className="panel-heading"><Icon name="cube"/><h2>Máquina virtual de Colima</h2></div>
      {runtime.kind !== 'colima' ? <Alert>Docker utiliza el kernel de Linux/WSL2. Sus recursos se administran desde el sistema operativo; NearProd no ejecuta sudo.</Alert> : !doctor && loadingDoctor ? <Skeleton label="Consultando estado y asignación de Colima" rows={6}/> : <>
        <div className="runtime-state" role="status"><span className={colimaRunning ? 'live-dot' : 'offline-dot'}/><strong>{runtimeBusy ? 'Operación en curso' : colimaRunning ? 'Colima en ejecución' : colimaState === 'stopped' ? 'Colima detenido' : colimaState === 'missing' ? 'Perfil no encontrado' : 'Estado de Colima no comprobado'}</strong>{loadingDoctor && <span className="hint">Actualizando…</span>}</div>
        <p className="field-help">El estado de la VM y la conexión con Docker Engine son comprobaciones distintas. {colimaRunning && !connected ? 'La VM está activa, pero Docker no responde: revisa el diagnóstico, no vuelvas a iniciarla.' : ''}</p>
        {colimaState === 'stopped' && connected && <Alert>Docker responde pero el diagnóstico del perfil indica que está detenido. Actualiza el diagnóstico antes de actuar.</Alert>}
        <div className="metric-pair"><div><span>RAM asignada a toda la VM</span><strong>{doctor?.allocation ? `${doctor.allocation.memoryGiB} GiB` : 'Sin datos'}</strong></div><div><span>CPU virtuales</span><strong>{doctor?.allocation?.cpus ?? '—'}</strong></div></div>
        <p className="hint">VM: {doctor?.allocation?.vmType || 'sin comprobar'} · montaje: {doctor?.allocation?.mountType || 'sin comprobar'}</p>
        <div className="form-grid"><Field label="RAM de la VM (GiB)" help="Límite compartido por Linux, Docker y todos los contenedores; no es una asignación por aplicación."><input disabled={cannotChange} type="number" step="0.5" min="0.5" value={memory} onChange={e => setMemory(e.target.value)}/></Field><Field label="CPU virtuales" help="Número de CPU disponibles en la VM. Cambiar recursos puede requerir reiniciarla."><input disabled={cannotChange} type="number" min="1" value={cpus} onChange={e => setCpus(e.target.value)}/></Field></div>
        <div className="inline-actions"><button disabled={cannotChange || !doctor?.allocation || !['running','stopped'].includes(colimaState || '')} onClick={() => void task(async () => setPreview(await api<ResourcePreview>('/runtime/preview',{memory:Number(memory),cpus:Number(cpus)})))}>Revisar cambio y alcance</button>
          {colimaState === 'stopped' && !connected && <button className="primary" disabled={cannotChange} onClick={() => {if(window.confirm('¿Iniciar el perfil Colima existente? No se creará otra VM ni se cambiará el contexto global.')) void task(async () => {await api('/runtime/actions',{action:'start',confirm:true});notify('Inicio de Colima solicitado. Consulta Actividad.');});}}><Icon name="play"/>Iniciar Colima</button>}
          {colimaRunning && !runtimeBusy && <span className="runtime-ok"><Icon name="check" size={16}/>Ya está iniciado</span>}
        </div><p className="hint">La revisión muestra TODAS las cargas afectadas antes de aplicar un cambio; cerrar NearProd no detiene Colima.</p>
      </>}
    </section></div>
    <section className="panel"><div className="panel-heading"><Icon name="activity"/><h2>Consumo observado</h2>{loadingMetrics && metrics && <span className="hint" role="status">Actualizando…</span>}</div>
      {!metrics && loadingMetrics ? <Skeleton label="Cargando consumo de recursos" rows={4}/> : metrics ? <><div className="metrics"><div><span>Memoria física del host</span><strong>{humanBytes(metrics.host.totalBytes)}</strong></div><div><span>Proceso NearProd</span><strong>{humanBytes(metrics.agent.rssBytes)}</strong></div><div><span>Disponible en Linux invitado</span><strong>{humanBytes(metrics.guest?.availableBytes)}</strong></div><div><span>Swap usado en invitado</span><strong>{metrics.guest ? humanBytes(metrics.guest.swapTotalBytes - metrics.guest.swapFreeBytes) : 'Sin datos'}</strong></div></div><p className="hint">{metrics.note} La pestaña del navegador no está incluida en el RSS del agente. No sumes VM y contenedores como consumos independientes.</p>
        {metrics.containers.length ? <div className="table-wrap"><table><thead><tr><th>Contenedor</th><th>CPU</th><th>RAM / límite</th></tr></thead><tbody>{metrics.containers.map(c => <tr key={c.id}><td>{c.name}</td><td>{c.cpu}</td><td>{c.memory}</td></tr>)}</tbody></table></div> : <p className="hint">{connected ? 'No hay métricas de contenedores activos.' : 'Docker no está conectado. Las métricas de contenedores no están disponibles.'}</p>}</> : <Alert>No fue posible cargar las métricas. Vuelve a consultar el diagnóstico.</Alert>}
    </section>
    <section className="panel"><div className="panel-heading"><Icon name="terminal"/><h2>Herramientas y versiones</h2></div><p className="field-help">Son herramientas distintas, no VMs adicionales. Docker puede responder aunque falte un plugin del cliente.</p>
      {!doctor && loadingDoctor ? <Skeleton label="Comprobando herramientas de Docker" rows={4}/> : doctor && <><p className="hint">NearProd {doctor.nearprod} · Go {doctor.goVersion} · {doctor.platform}</p><div className="tool-list">{doctor.tools.map(t => <div key={t.name} className="tool"><Icon name={t.available ? 'check' : 'warning'}/><strong>{t.name}</strong><span className="tool-status">{t.available ? 'Disponible' : t.status === 'plugin-not-registered' ? 'Instalado, pero Docker no encuentra el plugin' : 'No disponible para NearProd'}</span><code>{t.version}</code><p className="field-help">{t.purpose} <strong>{t.required ? 'Requerido para su función.' : 'No bloquea estado, logs ni detención.'}</strong></p>{!t.available && <p className="hint">{t.hint}</p>}</div>)}</div>{doctor.error && <Alert error>{doctor.error.message}</Alert>}
      {doctor.tools.some(t => !t.available && ['Compose','Buildx'].includes(t.name)) && <details className="advanced"><summary>Cómo reparar plugins instalados con Homebrew</summary><p>Primero comprueba si funcionan en tu terminal. Si allí funcionan pero NearProd no los detecta, reinicia el agente desde esa terminal para actualizar su entorno.</p><pre className="console">{'docker compose version\ndocker buildx version\n\n# Solo si faltan:\nbrew install docker-compose docker-buildx\n\n# Obtener la ruta de plugins:\necho "$(brew --prefix)/lib/docker/cli-plugins"'}</pre><p>En <code>~/.docker/config.json</code> añade esa ruta absoluta a <code>cliPluginsExtraDirs</code> sin eliminar otras claves. En Apple Silicon suele ser <code>/opt/homebrew/lib/docker/cli-plugins</code>.</p><pre className="console">{'"cliPluginsExtraDirs": ["/opt/homebrew/lib/docker/cli-plugins"]'}</pre><p>El fragmento es una propiedad JSON, no reemplaza el archivo entero. Después ejecuta <code>nearprod agent stop</code> y <code>nearprod ui</code>; no detienen tus contenedores.</p></details>}</>}
      <button disabled={busy} onClick={() => void task(async () => setUpdates(await api('/updates',{})))}>Comprobar actualizaciones conocidas</button><p className="hint">Consulta metadatos locales de Homebrew. No instala paquetes ni actualiza dependencias de proyectos.</p>
      {updates && <div className="update-results"><p>{updates.message}</p>{updates.items.length > 0 ? <div className="table-wrap"><table><thead><tr><th>Herramienta</th><th>Instalada</th><th>Versión conocida</th><th>Comando manual</th></tr></thead><tbody>{updates.items.map(i => <tr key={i.name}><td>{i.name}</td><td>{i.installed.join(', ')}</td><td>{i.latestKnown}</td><td><code>{i.command}</code></td></tr>)}</tbody></table></div> : <p className="hint">No hay actualizaciones registradas en esta consulta; no confirma que los metadatos estén al día.</p>}</div>}
    </section>
    {preview && <Modal title="Confirmar cambio global de Colima" subtitle="La operación afecta a toda la VM, no solo a NearProd." onClose={() => setPreview(null)}><Alert error>{preview.warning}</Alert><p>Asignación solicitada: <strong>{preview.memory} GiB · {preview.cpus} CPU</strong></p><h3>Contenedores activos afectados</h3>{preview.affected.length ? <ul className="hints">{preview.affected.map(c => <li key={c.id}>{c.name} · {c.project || 'fuera de Compose'}</li>)}</ul> : <p>No se observaron contenedores activos en esta revisión.</p>}<div className="modal-actions"><button onClick={() => setPreview(null)}>Cancelar</button><button className="danger" disabled={busy || runtimeBusy} onClick={() => void task(async () => {await api('/runtime/actions',{...preview,action:'configure',confirm:true});setPreview(null);notify('Cambio global solicitado. Consulta el resultado en Actividad.');})}>Aplicar cambio global</button></div></Modal>}
  </div>;
}
export function LogsDrawer({ stack, observed, onClose }: {stack: Stack; observed?: Observed; onClose: () => void}) {
  const [service, setService] = useState(''), [paused, setPaused] = useState(false), [lines, setLines] = useState<LogLine[]>([]), [state, setState] = useState('Conectando…'), [filter, setFilter] = useState('');
  const cursor = useRef(''), source = useRef<EventSource | null>(null), pre = useRef<HTMLPreElement>(null);
  useEffect(() => {cursor.current = ''; setLines([]);}, [stack.id, service]);
  useEffect(() => {
    if (paused) {setState('Pausado · seguimiento desconectado'); return;}
    setState('Conectando…');
    const query = new URLSearchParams({target: stack.id, follow:'true', tail:'100'}); if(service) query.set('service',service); if(cursor.current) query.set('since', cursor.current);
    const events = new EventSource(`/api/logs?${query}`); source.current = events;
    events.addEventListener('open', () => setState('En vivo'));
    events.addEventListener('line', (raw) => {const e = raw as MessageEvent; const line = JSON.parse(e.data) as LogLine; if(e.lastEventId) cursor.current = e.lastEventId; setLines(prev => [...prev, {...line, text:line.text.slice(-8000)}].slice(-400));});
    events.addEventListener('log-error', (raw) => {setState((JSON.parse((raw as MessageEvent).data) as {message:string}).message); events.close();});
    events.onerror = () => setState('Reconectando… Puede haber solapamientos o huecos.');
    return () => {events.close(); source.current = null;};
  }, [stack.id, service, paused]);
  useEffect(() => {if (!paused && pre.current) pre.current.scrollTop = pre.current.scrollHeight;}, [lines, paused]);
  const services = [...new Set(observed?.containers.map(c => c.service) || [])];
  return <section className="logs-drawer" aria-label="Logs en tiempo real"><div className="logs-header"><div><span className="eyebrow">LOGS EN TIEMPO REAL</span><h2>{stack.id}</h2></div><button className="icon-button" aria-label="Cerrar logs" onClick={onClose}><Icon name="close"/></button></div><div className="logs-toolbar"><label>Servicio<select aria-describedby="logs-service-help" value={service} onChange={e => setService(e.target.value)}><option value="">Todos (máximo 8 instancias)</option>{services.map(s => <option key={s} value={s}>{s}</option>)}</select></label><label>Filtro local<input aria-describedby="logs-filter-help" value={filter} onChange={e => setFilter(e.target.value)} placeholder="Filtrar salida…"/></label><button onClick={() => setPaused(!paused)}>{paused ? 'Reanudar' : 'Pausar'}</button><button onClick={() => setLines([])}>Limpiar vista</button></div><p className="sr-only" id="logs-service-help">Selecciona de qué servicio leer logs. No cambia los contenedores.</p><p className="sr-only" id="logs-filter-help">Filtra solo las líneas visibles en este panel; no cambia la aplicación ni el seguimiento.</p><div className="log-status"><span className={!paused && state === 'En vivo' ? 'live-dot' : 'dot'}/>{state}<span>Buffer: {lines.length}/400 líneas</span></div>{!lines.length && state === 'Conectando…' && <Skeleton label="Abriendo seguimiento de logs" rows={4}/>}<pre ref={pre} className="console logs-output">{lines.filter(l => !filter || l.text.toLowerCase().includes(filter.toLowerCase())).map((l,i) => <div className={l.stream === 'stderr' ? 'stderr' : ''} key={`${i}-${l.time}`}><span className="log-service">{l.service}</span> {l.text}</div>)}</pre><p className="hint">Los logs pueden contener secretos. Se filtran algunos valores conocidos, no existe una garantía de redacción completa. Cerrar esta vista libera el seguimiento, no detiene el contenedor.</p></section>;
}
// Prevent accidental unused imports when this file is extended by the project.
