http:
  routers:
    local-infra-ui:
      rule: Host(`infra.localhost`)
      entryPoints:
        - web
      service: local-infra-ui

  services:
    local-infra-ui:
      loadBalancer:
        servers:
          - url: http://host.docker.internal:5055
